# Fit Transform/predict

In [1]:
#fit :代表擬合，訓練模型
#transform:使用已經訓練過的模型來令資料轉換
#predict:使用已經訓練過的模型來預測結果
#fit_transform、fit_predict 同時訓練與得到轉換後的資料/預測結果

# 切分資料

In [3]:
import numpy as np
from sklearn.model_selection import train_test_split

In [4]:
x = np.arange(20).reshape((10,2))
y = np.arange(10)

In [8]:
print('Before splitting')

Before splitting


In [6]:
x  #模擬資料集

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [7]:
y  #模擬label 答案

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
x.shape

(10, 2)

In [10]:
y.shape

(10,)

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x,y ,test_size=0.3)  #將資料切分，7成training 3成test 

In [ ]:
print('After splitting')

In [12]:
x_train  #訓練資料集的資料集

array([[ 4,  5],
       [ 2,  3],
       [18, 19],
       [10, 11],
       [ 0,  1],
       [12, 13],
       [16, 17]])

In [13]:
x_test #測試資料集的資料集

array([[ 8,  9],
       [14, 15],
       [ 6,  7]])

In [14]:
y_train  #訓練資料集的答案

array([2, 1, 9, 5, 0, 6, 8])

In [16]:
y_test  #測試資料集的答案

array([4, 7, 3])

# Preprocessing Data

In [17]:
from sklearn import preprocessing
import numpy as np

In [19]:
x_train1 = np.array([[100, -1, 2],
                   [900, 0, 0],
                    [200, 1,-1]])
scaler = preprocessing.StandardScaler().fit(x_train1)    #指訓練完的模型  scaler 為訓練出來的模型
x_train1 = scaler.transform(x_train1)                    #然後再去transform

print("after standardiztion.....")
print(f'x_train1:{x_train1}')

after standardiztion.....
x_train1:[[-0.84292723 -1.22474487  1.33630621]
 [ 1.40487872  0.         -0.26726124]
 [-0.56195149  1.22474487 -1.06904497]]


In [20]:
# 下頭的x_test1 資料 就是拿上頭訓練出來的模型scaler 去做資料轉換的動作

In [21]:
x_test1 = np.array([[-1,1,0]])
x_test1 = scaler.transform(x_test1)  #用上頭訓練出來的scaler去做轉換
print(f'x_test1:\n {x_test1}')

x_test1:
 [[-1.12671273  1.22474487 -0.26726124]]


# fit_transform api 會直接得到訓練完轉成的資料

In [22]:
x_train2 = np.array([[100,-1,2],
                  [900,0,0],
                  [200,1,-1]])
x_train2 = preprocessing.StandardScaler().fit_transform(x_train)

print("after standardiztion......")

print(f'x_train2:\n {x_train2}')       #所得到的x_train2就為轉換好的資料，而不是模型

after standardiztion......
x_train2:
 [[-0.74838327 -0.74838327]
 [-1.05654109 -1.05654109]
 [ 1.40872145  1.40872145]
 [ 0.17609018  0.17609018]
 [-1.3646989  -1.3646989 ]
 [ 0.484248    0.484248  ]
 [ 1.10056363  1.10056363]]
